coverage:
  status:
    project:
      default:
        informational: false
        target: auto
        threshold: 5%

# Common exclusions:
#  * build artifacts (bin/obj)
#  * generated/designer files
#  * assets/config files that cannot contain executable code
#  * test projects (their lines should not count against the product code)
ignore:
  - "**/bin/**"
  - "**/obj/**"
  - "**/*.designer.cs"
  - "**/*.g.cs"
  - "**/*.g.i.cs"
  - "**/*.Generated.cs"
  - "BrickBreaker.ConsoleClient/Assets/**"
  - "BrickBreaker.Storage/Properties/appsettings.json"
  - "BrickBreaker.Tests/**"
  # Console rendering, state-machine UI, and Spectre front-end pieces are highly coupled to
  # terminal state and ANSI cursor positions, so we accept visual/manual testing there.
  - "BrickBreaker.ConsoleClient/Game/**"
  - "BrickBreaker.ConsoleClient/Ui/**"
  # Native interop/audio glue is similarly impractical to cover in CI.
  - "BrickBreaker.ConsoleClient/Game/Systems/ConsoleRenderer.cs"
  - "BrickBreaker.ConsoleClient/Game/BrickBreakerGame.cs"
